FROM python:latest

RUN pip install numpy \
            scipy \
            argparse \
            kafka-python

COPY ./src/hawkes_estimator/ /HawkesEstimator 
WORKDIR /HawkesEstimator/app
CMD export RDK_PREFIX=/usr/local && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RDK_PREFIX/lib && export KAFKA_PATH=/kafka-2.4.1-src && python3 hawkes_estimator.py --broker-list localhost:9092
