{
 "title": "Tweetoscope",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 5 hottest cascades [time_window=1200]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "AVG Absolute Relative Error [time_window=1200][2 min]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"python_app\",__name__=\"ares\",time_window=\"1200\",type=\"ARE\"}[2m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time({job=\"python_app\",__name__=\"ares\",time_window=\"1200\",type=\"ARE_RF\"}[2m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top 5 hottest cascade in the last two minutes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"1\", time_window=\"1200\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"2\",time_wndow=\"1200\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"3\", time_window=\"1200\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"4\", time_window=\"1200\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"5\", time_window=\"1200\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    }
   ]
  },
  {
   "title": "Tweet ID of the top 5 hottest cascade in the last two minutes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"1\", time_window=\"1200\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"2\", time_window=\"1200\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"3\", time_window=\"1200\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"4\", time_window=\"1200\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"5\", time_window=\"1200\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    }
   ]
  },
  {
   "title": "Top 5 hottest cascades [time_window=600]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "AVG Absolute Relative Error [time_window=600][2 min]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"python_app\",__name__=\"ares\",time_window=\"600\",type=\"ARE\"}[2m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time({job=\"python_app\",__name__=\"ares\",time_window=\"600\",type=\"ARE_RF\"}[2m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top 5 hottest cascade in the last two minutes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"1\", time_window=\"600\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"2\",time_window=\"600\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"3\", time_window=\"600\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"4\", time_window=\"600\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"n_supp\",level=\"5\", time_window=\"600\"}",
     "legendFormat": "N_tot : {{level}} hottest cascade"
    }
   ]
  },
  {
   "title": "Tweet ID of the top 5 hottest cascade in the last two minutes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"1\", time_window=\"600\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"2\", time_window=\"600\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"3\", time_window=\"600\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"4\", time_window=\"600\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    },
    {
     "expr": "{job=\"python_app\",__name__=\"tweet_id\", level=\"5\", time_window=\"600\"}",
     "legendFormat": "Tweet ID : {{level}} hottest cascade"
    }
   ]
  },
  {
   "title": "Stats over hawkes/predictor/learner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Number of msg sent to predictor in the last minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"hawkes_estimator\", level=\"debug\"}[1m])"
    }
   ]
  },
  {
   "title": "Number of alert msg sent in the last minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"predictor\", level=\"debug\"} |= \"Alert\"[1m])"
    }
   ]
  },
  {
   "title": "Number of time RF model has been update [600]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"learner\",level=\"info\"} |= \"Time window :   600\"[15m])"
    }
   ]
  },
  {
   "title": "Number of stats msg sent in the last minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"predictor\",level=\"debug\"} |= \"Stat\"[1m])"
    }
   ]
  },
  {
   "title": "Number of sample msg sent in the last minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"predictor\", level=\"debug\"} |= \"Sample\"[1m])"
    }
   ]
  },
  {
   "title": "Number of time RF model has been update [1200]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"learner\",level=\"info\"} |= \"Time window :  1200\"[15m])"
    }
   ]
  },
  { "title": "Stats over collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Number of tweets processed in the last minute",
   "type": "stat",
   "description": "Number of tweets processed by the tweet collector in the last minute (sliding window)",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"collector\", level=\"info\"} |= \"new\"[1m])"
    }
   ]
  },
  {
   "title": "Number of msg sent to hawkes in the last minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"collector\", level=\"debug\"} |= \"serie\"[1m])"
    }
   ]
  },
  {
   "title": "Number of msg sent to predicator in the last minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"collector\",level=\"debug\"}|= \"Size\"[1m])"
    }
   ]
  },
  {
   "title": "Number of retweet ignored in the last minute",
   "type": "gauge",
   "description": "Number of retweet ignored in the last minute because we considered the cascade terminated",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"collector\", level=\"warning\"}[1m])"
    }
   ]
  },
  {
   "title": "Number of retweet ignored due to missed tweet in the last minute",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"collector\", level=\"error\"}[1m])"
    }
   ]
  }
 ]
}