FROM alpine

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

RUN pip install argparse \
            kafka-python \
            termcolor


COPY ./src/logger/ /Logger 
WORKDIR /Logger
ARG src
ENV src $src
ARG lvl
ENV lvl $lvl
CMD python3 logger.py --broker-list kafka-service:9092 --logs_topic logs --levels $lvl --sources $src
